---
name: 'slamco'
version: '1.0.0'
config-version: 2

profile: 'slamco'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

# These directories are cleaned by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

models:
  slamco:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
